resources:
  - name: code
    type: git
    source: {uri: 'https://github.com/schehata/gofixtures'}

jobs:
- name: lint
  plan:
    - get: code
      trigger: true
    - task:  test
      file: code/ci/tasks/lint.yml

- name: test
  plan:
    - get: code
      passed: [lint]
      trigger: true
    - task:  test
      file: code/ci/tasks/test.yml

        
- name: build
  plan:
  - get: code
    passed: [test]
    trigger: true
  - task: build
    file: code/ci/tasks/build.yml
    

