resources:
  - name: code
    type: git
    source: {url: 'https://github.com/ishehata/gofixtures'}
    check_every: 30

jobs:
- name: test
  plan:
    - get: code
      trigger: true
    - task:  test
      file: tasks/test.yml

- name: build
  plan:
  - get: code
    trigger: true
  - task: build
    file: tasks/build.yml
    

